### ISSUE TITLE
Compilation errors with gcc version 4.8 

### ISSUE THREAD

**Issue by CGarces** [CGarces/rtl8192eu-linux-driver#3]
~~The branch is failing compiling with gcc version 4.9.2~~
In fact was 4.8

```
$ gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
```
```
$ make 
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.16.0-4-amd64/build M=/media/hdd/Development/rtl8192eu-linux-driver  modules
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  CC [M]  /media/hdd/Development/rtl8192eu-linux-driver/core/rtw_cmd.o
cc1: error: -Werror=date-time: no option -Wdate-time
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/media/hdd/Development/rtl8192eu-linux-driver/core/rtw_cmd.o' failed
make[4]: *** [/media/hdd/Development/rtl8192eu-linux-driver/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/Makefile:1354: recipe for target '_module_/media/hdd/Development/rtl8192eu-linux-driver' failed
make[3]: *** [_module_/media/hdd/Development/rtl8192eu-linux-driver] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:1697: recipe for target 'modules' failed
make: *** [modules] Error 2
```

The problem comes from [this commit](https://github.com/CGarces/rtl8192eu-linux-driver/commit/8147981778f743229ee16068ec958f43025aea40)

Note than in the original tarball that line is commented to avoid compilation issues.

@masterzorag, can you explain the motivation of un-comment that line?

**Comment by masterzorag** [comment]
Hmmm... I've uncommented that line just as stated by Realtek devs in the provided comment;
By the way, the error is:
cc1: error: -Werror=date-time: no option -Wdate-time
That's sounds different from the flag passed by uncommented line...

**Comment by CGarces** [comment]
Hi.

It's a problem with my debian build enviroment.
By some reason gcc -v get me 
`gcc version 4.9.2 (Debian 4.9.2-10)` 

But if I execute the make with the extra flag `-v` i get
`gcc version 4.8.4 (Debian 4.8.4-1)`

The original Make file from mange works with 4.8 and 4.9 so I'll try to keep the compatibility.

**Comment by CGarces** [comment]
I have reordered the commits, and remove the commit with the `EXTRA_CFLAGS += -Wno-error=date-time`
If fails with any version of gcc will fail in the same way than the original branch from Mange, so is ok for me.

BTW I don't get any error after remove the commit.

If you compile a very old version like [that one](https://github.com/Mange/rtl8192eu-linux-driver/commit/6793baedf50fbf0822d2b87a1070527c0fd0685e), it needs the extra flag.

But [after this commit](https://github.com/Mange/rtl8192eu-linux-driver/commit/1b39426f323f7a52f43d2eb1965f1c6a15df2734), is no longer need because adds `EXTRA_CFLAGS += -Wno-date-time`

I don't know the impact of use  -Wno-date-time vs -Wno-error=date-time but I'll keep the first one keep the compatibility with GCC 4.8

**Comment by masterzorag** [comment]
As stated [here](https://gcc.gnu.org/gcc-4.9/changes.html)

The -Wdate-time option has been *added* for the C, C++ and Fortran compilers, which warns when the __DATE__, __TIME__ or __TIMESTAMP__ macros are used. Those macros might prevent bit-wise-identical reproducible compilations.

**Comment by CGarces** [comment]
Thanks, but I still not understand the implications of  **-Wno-date-time** vs **-Wno-error=date-time**

**Comment by masterzorag** [comment]
They exists just from gcc 4.9:
the first turns off warnings, the second makes warnings not be errors.
(Realtek commented the second one)
