### ISSUE TITLE
rtl8192eu

### ISSUE THREAD

**Issue by bax-by** [CGarces/rtl8192eu-linux-driver#39]
hello maybe you can help me. install rtl8192eu adapter driver for kali with kernel 5.19
after the update, the old drivers do not work, I almost do not understand this, after the make command I have an error with a reference to the kernel. perhaps you have a solution to this problem.
thanks in advance

**Comment by CGarces** [comment]
Please don't use this repository, is just a fork of https://github.com/Mange/rtl8192eu-linux-driver
