### ISSUE TITLE
AIRMON-ng shows driver as ??????

### ISSUE THREAD

**Issue by psharma04** [CGarces/rtl8192eu-linux-driver#5]
When using this driver on Raspbian 9 (Raspberry Pi 2 Model B), airmon-ng states that the driver is ??????, and fails to enter monitor mode. Is there any reason for this? Is monitor mode going to be supported at any point?

**Comment by CGarces** [comment]
Hi
This repository is just a fork, please use https://github.com/Mange/rtl8192eu-linux-driver and open your issues there.
